version: '3.8'

services:
  app:
    build: 
      context: .
      target: app
      dockerfile: dev.Dockerfile
      args:
        PHP_VERSION_ARG: ${PHP_VERSION}
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./symfony:/var/www/app:rw

  db:
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    env_file:
      - .env
    volumes:
      - ./docker/db/log:/var/log/mysql:rw

  web:
    image: nginx:${NGINX_VERSION}
    build:
      context: .
      target: web
      args:
        NGINX_VERSION_ARG: ${NGINX_VERSION}
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./docker/web/log:/var/log/nginx:rw
      - ./docker/web/config/nginx.conf:/opt/nginx-confs/default.conf.dist:ro

  cache:
    image: redis:${REDIS_VERSION}-alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./docker/cache/data:/data:rw