parameters:
    env(COMPOSE_PROJECT_NAME): 'car-showroom'

framework:
    cache:
        default_redis_provider: 'redis://%env(REDIS_HOST)%:%env(int:REDIS_PORT)%'
        prefix_seed: '%env(COMPOSE_PROJECT_NAME)%'

        pools:
            auth_pool:
                adapter: cache.adapter.redis
                default_lifetime: '%env(int:AUTH_TOKEN_LIFETIME)%'