nelmio_api_doc:
  areas:
    path_patterns:
      - ^/api(?!/doc$)
  documentation:
    servers:
      - url: 'http://localhost'
        description: API over HTTPS
    info:
      title: car-showroom
      description: API for Car Showroom
      version: '%api.version%'
