security:
    enable_authenticator_manager: true
    encoders:
        App\Entity\User:
            algorithm: native
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        user_provider:
            id: App\Provider\UserProvider
    firewalls:
        login:
            provider: user_provider
            pattern: '/%api.prefix%/auth/login$'
            custom_authenticators:
                - App\Security\Authenticator

        main:
            pattern: ^/api
            stateless: true
            logout:
                path: '/%api.prefix%/auth/logout'
            custom_authenticators:
                - App\Security\TokenAuthenticator

    role_hierarchy:
        ROLE_DIRECTOR: ROLE_MANAGER
        ROLE_MANAGER: ROLE_GUEST

    access_control:
        - { path: ^/%api.prefix%/users, roles: ROLE_DIRECTOR, methods: [POST, PUT, PATCH, DELETE]}
        - { path: ^/%api.prefix%/showrooms, roles: ROLE_DIRECTOR, methods: [POST, PUT, PATCH, DELETE]}
        - { path: ^/%api.prefix%/users, roles: ROLE_MANAGER }
        - { path: ^/%api.prefix%/purchases, roles: ROLE_MANAGER }
